builds:
  - main: ./cmd/killager
    binary: killager
    ldflags:
    - -extldflags '-static' 
    - -X github.com/4armed/killager/pkg/config.GitVersion={{.Version}}
    env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
- format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
